import Navigation from "@/components/Navigation/page";
import "./globals.css";

export const metadata = {
  title: "Order Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigation/>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
